### ISSUE TITLE
PCFLib doesn't generate Bob's input gates unless set_bob_inputs called

### ISSUE THREAD

**Issue by drwhomphd** [cryptouva/pcf#3]
PCFLib was not generating Bob's input gates (but was generating at least some of Alice's input gates) when setup_bob_inputs_from_string (or the hex equivalent) was not called. This is problematic to anyone using PCFLib as a tool to generate a circuit construction without the intention to immediately generate and evaluate it, i.e., everyone using PCFLib as a third-party library. A correct and complete circuit should be generated whether or not setup_alice_inputs_from_string and/or setup_bob_inputs_from_string is called.

**Comment by benkreuter** [comment]
I am not sure I am understanding the problem.  setup_bob_inputs_from_string is not a pcflib function, it is part of a test harness in test.c

**Comment by drwhomphd** [comment]
Ben, my means for reproduction was commenting out "setup_alice_inputs_from_string" and "setup_bob_inputs_from_string" from circgen.c, running the program, and seeing the output. When they are commented out, Bob has no input wires generated. Both those function appear to modify the st variable which I assume is the PCFLib state for the circuit. Given the point of that library is to provide an implementation independent circuit description, there should be no requirement to set the input values for the circuit (as input values are only going to be known after OT is performed).

**Comment by benkreuter** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On Mon, 17 Feb 2014 15:39:31 -0800
DrWhom notifications@github.com wrote:

> Ben, my means for reproduction was commenting out
> "setup_alice_inputs_from_string" and "setup_bob_inputs_from_string"
> from circgen.c, running the program, and seeing the output. When they
> are commented out, Bob has no input wires generated.

Right, note that st->bob_input_size is set by the
setup_bob_inputs_from_string function.  pcflib will not emit input
gates for inputs beyond the input size that is set there in order to
simplify the implementation of callback functions; it assumes a 0 value
as the input.

> Both those function appear to modify the st variable which I assume
> is the PCFLib state for the circuit. Given the point of that library
> is to provide an implementation independent circuit description, there
> should be no requirement to set the input values for the circuit (as
> input values are only going to be known after OT is performed). 

We assume that the inputs will not rely on any intermediate state from
the circuit; this is probably safe to assume in the context of SFE
since the intermediate states are not known to the parties.  Under that
assumption we can require that input values be known before the circuit
evaluation begins, as well as the number of inputs.  This is the common
pattern in the kinds of systems we are dealing with e.g. in the case of
Yao protocols, input wire keys are computed before garbling (or at
least independent from garbling) and OT is performed before circuit
generation (ditto).

The only change I can see being necessary here is to add a function
that allows client code to set the input sizes and values for the
parties.  This would help to hide implementation details about the
internal state.
- -- Ben
  -----BEGIN PGP SIGNATURE-----
  Version: GnuPG v2.0.14 (GNU/Linux)

iQIcBAEBAgAGBQJTAqHGAAoJEP3W2K8t6K+jQvsP/2uw6Is5o1cwZ5kKpl7WyjCZ
WrKsyr0frvOXAIqOX4UuQYlM6Qf5vVaXr8rWnnvyaWJ1E0o1LDzOy+HdQ/Ekw13t
3IH+Yatf8ZkvxK63yENBiplRBeB96ZxekYVGjn2ZV3DaXVqyD0YVENKh8nBGJ3Op
dis5FVmh6RacLisTXJJqzfvY58BIt50y5NlfIBE2Dd6qnUmgj5Dqp0rSBAilyb3W
zSQpBsYg3aDlKOAaxgXNdEF5M5D367O6g1bUmSuAWEsGXHET9YoxIz82nWANF5Sk
19+gz0xJ0MOoGFwhwbxYEIwpTv9jONuBCz/Fu9L91Kv/NJR3t6ZTgZIMsu21imwG
pjXIPKnaFQ2A655u07ssj1+d6rwPjMjTPcOoL0bPs7zBYoMGMbnzdcYBtf70yDaz
rT4BTAYnBpPWRG+1M4dF1ZjK5wn1V0jPzgZWaGSADpvKkksH1PAb+ZgMpmRjMpRn
zn9yoUHjGzIAT4WwsHruqos1szCXaC2QB9y9ORwkFo/1gUmPWB67m09e6/OUbonW
HyRmdWb7TwLtxYpJ+AfK3I6MAPNfwctS2UgJIMfGNLioTGsswnGP6xBtFZK9obV2
sfaICeBL+CTInOYfAhmQONG2LgEpQMG0I52uumxRCt/PVmqJzGl9tZuLWlGRLxHf
bTpMrr5S0WWxn6ahjRE8
=M7dP
-----END PGP SIGNATURE-----

**Comment by drwhomphd** [comment]
In this case I think a useful default in circgen is to manually set the bob_size and alice_size to the maximum size possible for the variable. I'll make sure this is the case in the pypcf library and submit a patch to cirgen.c if there aren't any qualms to the change? The reasoning is that cirgen.c will be used by most as a reference implementation to base their circuit construction programs on (i.e., cases where they will take the output of PCFLib and construct their own circuits).

**Comment by benkreuter** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On Mon, 17 Feb 2014 16:18:46 -0800
DrWhom notifications@github.com wrote:

> In this case I think a useful default in circgen is to manually set
> the bob_size and alice_size to the maximum size possible for the
> variable. I'll make sure this is the case in the pypcf library and
> submit a patch to cirgen.c if there aren't any qualms to the change?
> The reasoning is that cirgen.c will be used by most as a reference
> implementation to base their circuit construction programs on (i.e.,
> cases where they will take the output of PCFLib and construct their
> own circuits). 

Seems reasonable.
- -- Ben
  -----BEGIN PGP SIGNATURE-----
  Version: GnuPG v2.0.14 (GNU/Linux)

iQIcBAEBAgAGBQJTAsSkAAoJEP3W2K8t6K+jU+gQAJAsWOSqmZYKwbBtP3MEM2Bl
mxdPnnxsec0Zi/TbAdXhDE/I2H2z174logZgTSKaiP48AhLlqlTmpeQjzGzvWsZg
eVC7cfMhLZOOZeG3ZyM5blhNyK86h8V6nRnOwknq40tyn3Rm0yfSNRzdRrf+L0JU
mj4kDJHLzPMAhUz3kXvSXNi5isxXb7uj6ok/sufdjhfCrapcnweHPVsmXgkllaaa
PyyKGTQKf+ArJ81WYpHIS9zjJjy3Bus8kV1OAUohuzOLAhFCjJjdcngDIK02Vpzw
3RmksnJpCmGgtFOmSRUJqMbRKobPbFmyv/YaPrZM1YczR0LJ0d2OFm07jphgtYYa
JorY6VEi8JqULVOcUe3lT4anb3904xGA1GJuHmJgIQcNhUijqv7pLBOVvPcthZL9
gRFNz6iBckPeiQhaFgYK2FoupgqBVq4NOGOn2qB8at+AWTAmDKk6jeW3v0AyRTc5
wfwrObSb8apOf+pTymnOpew5N0LjRJjxGQsTGOrlDjdi9xBKBusvmEmvlix4VlzU
TfYVLSgNGvlB1DA3OSkiIFD50zFXTAPYP0pKIchtp1L9xQ0JY0upW6aXV+gLegt6
4wpagq7suUYWVEoYjoYdvZDR4Wp8mjS2n2Kl3Wl6Q1/otqSliRJvDerMGwWSLIXW
CwdtJPTG5X9Ub2YH1Sv5
=Ma6h
-----END PGP SIGNATURE-----

**Comment by drwhomphd** [comment]
Issue handled in  commit 95e95051255725824865d5677dae21628e229d23.
